// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC84xAbGj4Owoy-XUuPXMyQe_grLZ49G3c',
    appId: '1:827914509813:web:a4761d5ff69ec6a6d594bc',
    messagingSenderId: '827914509813',
    projectId: 'stt-notes-474506',
    authDomain: 'stt-notes-474506.firebaseapp.com',
    storageBucket: 'stt-notes-474506.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf0I8BqgedPHj_0Ru6wmKB5OGwvg1r2_8',
    appId: '1:827914509813:android:f4d45b696148869fd594bc',
    messagingSenderId: '827914509813',
    projectId: 'stt-notes-474506',
    storageBucket: 'stt-notes-474506.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFzeqxeR3ZsW7-VIH08MiutQ2PvJHRcZ0',
    appId: '1:827914509813:ios:1e988e1ea0119940d594bc',
    messagingSenderId: '827914509813',
    projectId: 'stt-notes-474506',
    storageBucket: 'stt-notes-474506.firebasestorage.app',
    iosClientId: '827914509813-lc31qdlduthoq1uq8a1ms921au7uv118.apps.googleusercontent.com',
    iosBundleId: 'com.example.stt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC84xAbGj4Owoy-XUuPXMyQe_grLZ49G3c',
    appId: '1:827914509813:web:389c69407a86437fd594bc',
    messagingSenderId: '827914509813',
    projectId: 'stt-notes-474506',
    authDomain: 'stt-notes-474506.firebaseapp.com',
    storageBucket: 'stt-notes-474506.firebasestorage.app',
  );
}
